#!/usr/bin/env bash
# AssetCore — Cloud Setup Script
# Chạy 1 lần sau khi cài app trên server mới.
#
# Cách dùng (từ thư mục bench):
#   bash apps/assetcore/scripts/setup-cloud.sh <site-name>
#
# Ví dụ:
#   bash apps/assetcore/scripts/setup-cloud.sh assetcore.example.com
#
# Script sẽ:
#   1. Tạo frontend/.env cho site
#   2. Build Vue frontend (npm ci + npm run build)
#   3. Tạo nginx config snippet cho AssetCore FE
#   4. Hướng dẫn bước tiếp theo

set -e

SITE="${1:-}"
if [[ -z "$SITE" ]]; then
  echo "LỖI: Thiếu tên site."
  echo "Dùng: bash apps/assetcore/scripts/setup-cloud.sh <site-name>"
  exit 1
fi

BENCH_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
FRONTEND_DIR="$BENCH_DIR/apps/assetcore/frontend"
NGINX_SNIPPET="$BENCH_DIR/config/nginx.conf.d/assetcore-frontend.conf"

echo "==> AssetCore Cloud Setup"
echo "    Bench : $BENCH_DIR"
echo "    Site  : $SITE"
echo "    FE    : $FRONTEND_DIR"
echo ""

# ── 1. Kiểm tra Node.js ─────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  echo "LỖI: Node.js không có trong PATH. Cài Node.js 20+:"
  echo "  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
  echo "  sudo apt install -y nodejs"
  exit 1
fi

NODE_VER=$(node --version)
NODE_MAJOR=$(echo "$NODE_VER" | tr -d 'v' | cut -d. -f1)
if (( NODE_MAJOR < 20 )); then
  echo "LỖI: Node.js $NODE_VER quá cũ. Cần Node.js >= 20."
  exit 1
fi
echo "✓ Node.js $NODE_VER"

# ── 2. Tạo frontend/.env ─────────────────────────────────────────────────────
ENV_FILE="$FRONTEND_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" << EOF
VITE_FRAPPE_URL=http://localhost:8000
VITE_FRAPPE_SITE=$SITE
VITE_SERVE_FRAPPE_FILES=0
EOF
  echo "✓ Tạo frontend/.env"
else
  echo "✓ frontend/.env đã có, giữ nguyên."
fi

# ── 3. Build frontend ────────────────────────────────────────────────────────
echo ""
echo "==> Build Vue frontend..."
cd "$FRONTEND_DIR"

if [[ ! -d "node_modules" ]]; then
  echo "    Running npm ci..."
  npm ci
fi

npm run build
echo "✓ Build xong → $FRONTEND_DIR/dist/"

# ── 4. Tạo nginx config snippet ──────────────────────────────────────────────
echo ""
echo "==> Tạo nginx config snippet..."
mkdir -p "$(dirname "$NGINX_SNIPPET")"

cat > "$NGINX_SNIPPET" << NGINX
# AssetCore Frontend — auto-generated by setup-cloud.sh
# Đặt trong server block của site $SITE

# Serve Vue SPA từ frontend/dist/
location / {
    root $FRONTEND_DIR/dist;
    try_files \$uri \$uri/ /index.html;

    location ~* \.(js|css|woff2?|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}

# Proxy API về Frappe gunicorn
location /api/ {
    proxy_pass         http://127.0.0.1:8000;
    proxy_set_header   Host \$host;
    proxy_set_header   X-Real-IP \$remote_addr;
    proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto \$scheme;
    proxy_read_timeout 120s;
    proxy_buffering    off;
    client_max_body_size 50m;
}

location /files/ {
    proxy_pass       http://127.0.0.1:8000;
    proxy_set_header Host \$host;
    client_max_body_size 100m;
}

location /private/files/ {
    proxy_pass       http://127.0.0.1:8000;
    proxy_set_header Host \$host;
}

location /socket.io/ {
    proxy_pass             http://127.0.0.1:9000;
    proxy_http_version     1.1;
    proxy_set_header       Upgrade \$http_upgrade;
    proxy_set_header       Connection "upgrade";
    proxy_set_header       Host \$host;
}
NGINX

echo "✓ Nginx snippet → $NGINX_SNIPPET"

# ── 5. Tổng kết ──────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  AssetCore setup xong. Bước tiếp theo:"
echo ""
echo "  1. Setup Frappe nginx (nếu chưa):"
echo "     bench setup nginx"
echo ""
echo "  2. Chỉnh /etc/nginx/sites-available/<site> để include snippet:"
echo "     (xoá block location / mặc định của Frappe, thêm vào:)"
echo "     include $NGINX_SNIPPET;"
echo "     HOẶC copy nội dung snippet vào trong server block"
echo ""
echo "  3. Reload nginx:"
echo "     sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "  4. (Tuỳ chọn) Cài SSL:"
echo "     sudo certbot --nginx -d $SITE"
echo ""
echo "  App sẽ chạy tại: https://$SITE"
echo "============================================================"
