<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import QRCode from 'qrcode'
import { generateQrLabel } from '@/api/imm04'
import LoadingSpinner from '@/components/common/LoadingSpinner.vue'
import type { QrLabelData } from '@/types/imm04'

const props = defineProps<{
  name: string
}>()

const labelData = ref<QrLabelData | null>(null)
const loading = ref(false)
const error = ref<string | null>(null)
const qrDataUrl = ref<string>('')

async function generateQrImage(value: string) {
  try {
    qrDataUrl.value = await QRCode.toDataURL(value, {
      width: 160,
      margin: 1,
      color: { dark: '#000000', light: '#ffffff' },
      errorCorrectionLevel: 'M',
    })
  } catch {
    qrDataUrl.value = ''
  }
}

async function fetchLabel() {
  loading.value = true
  error.value = null
  try {
    const res = await generateQrLabel(props.name)
    if (res.success && res.data) {
      labelData.value = res.data
      await generateQrImage(res.data.qr_value)
    } else {
      error.value = res.error ?? 'Không thể tải dữ liệu QR'
    }
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Lỗi không xác định'
  } finally {
    loading.value = false
  }
}

function handlePrint() {
  window.print()
}

watch(() => props.name, fetchLabel)
onMounted(fetchLabel)
</script>

<template>
  <div>
    <LoadingSpinner v-if="loading" label="Đang tải dữ liệu QR..." />

    <div v-else-if="error" class="text-red-600 text-sm p-4 bg-red-50 rounded-lg">
      {{ error }}
    </div>

    <div v-else-if="labelData" class="space-y-4">
      <!-- Label Preview -->
      <div
        id="qr-label-print"
        class="border-2 border-gray-800 rounded-lg p-4 max-w-xs mx-auto bg-white font-mono"
      >
        <!-- Header -->
        <div class="text-center border-b border-gray-300 pb-2 mb-3">
          <p class="text-xs font-bold text-blue-900">{{ labelData.label.title }}</p>
        </div>

        <!-- QR Code image generated by qrcode library -->
        <div class="flex justify-center mb-3">
          <img
            v-if="qrDataUrl"
            :src="qrDataUrl"
            alt="QR Code"
            class="w-28 h-28"
            style="image-rendering: pixelated;"
          />
          <div v-else class="w-28 h-28 bg-gray-100 flex items-center justify-center rounded text-xs text-gray-400">
            QR Error
          </div>
        </div>

        <!-- Label fields -->
        <div class="space-y-1 text-xs">
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">ID Phiếu:</span>
            <span class="font-bold">{{ labelData.label.commissioning_id }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">QR Nội bộ:</span>
            <span class="font-bold text-blue-700">{{ labelData.label.internal_qr }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">Serial NSX:</span>
            <span class="font-bold">{{ labelData.label.vendor_serial }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">Model:</span>
            <span class="font-bold truncate max-w-28">{{ labelData.label.model }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">Khoa:</span>
            <span class="font-bold">{{ labelData.label.dept }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">Mã BYT:</span>
            <span class="font-bold">{{ labelData.label.moh_code }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">Lắp đặt:</span>
            <span class="font-bold">{{ labelData.label.installation_date }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">Tài sản:</span>
            <span class="font-bold text-green-700">{{ labelData.label.asset_id }}</span>
          </div>
          <div class="flex justify-between gap-2">
            <span class="text-gray-500">Trạng thái:</span>
            <span class="font-bold">{{ labelData.label.status }}</span>
          </div>
        </div>

        <!-- Footer -->
        <div class="border-t border-gray-300 mt-2 pt-2 text-center">
          <p class="text-xs text-gray-400">In ngày: {{ labelData.label.print_date }}</p>
        </div>
      </div>

      <!-- Actions -->
      <div class="flex gap-3 justify-center">
        <button class="btn-primary" @click="handlePrint">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          In nhãn
        </button>
        <button class="btn-secondary" @click="fetchLabel">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          Tải lại
        </button>
      </div>
    </div>
  </div>
</template>

<style>
@media print {
  body * {
    visibility: hidden;
  }
  #qr-label-print,
  #qr-label-print * {
    visibility: visible;
  }
  #qr-label-print {
    position: absolute;
    top: 0;
    left: 0;
    width: 280px;
    border: 2px solid #1f2937 !important;
    margin: 0;
    padding: 16px;
    box-shadow: none;
  }
}
</style>
